In [144]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [145]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           9939 non-null   object
 6   Age              9798 non-null   float64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(3), int64(8), object(3)
memory usage: 1.1+ MB

In [147]:
df.drop(columns=['CustomerId', 'Surname', 'RowNumber'], axis = 1, inplace = True)

In [148]:
df.columns.unique()

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

In [149]:
df.Gender.value_counts()

Gender
Male      5423
Female    4516
Name: count, dtype: int64

In [150]:
df['Gender']= df['Gender'].fillna('Male')

In [151]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  object
 2   Gender           10000 non-null  object
 3   Age              9798 non-null   float64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(3), int64(6), object(2)
memory usage: 859.5+ KB

**Label Encoding**

In [152]:
le = preprocessing.LabelEncoder()
df['Gender_Label']= le.fit_transform(df.Gender.values)
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_Label
0,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1,0
1,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0,0
2,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1,0
3,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0,0
4,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0,0

In [153]:
df.Gender.value_counts()

Gender
Male      5484
Female    4516
Name: count, dtype: int64

**One Hot Encoding**

In [154]:
one_hot = pd.get_dummies(df['Geography'])

In [155]:
one_hot = one_hot.astype(int)

In [156]:
one_hot

      France  Germany  Spain
0          1        0      0
1          0        0      1
2          1        0      0
3          1        0      0
4          0        0      1
...      ...      ...    ...
9995       1        0      0
9996       1        0      0
9997       1        0      0
9998       0        1      0
9999       1        0      0

[10000 rows x 3 columns]

In [157]:
df_dummies = pd.concat([df, one_hot], axis = 1)

In [158]:
df_dummies

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_Label,France,Germany,Spain
0,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1,0,1,0,0
1,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0,0,0,0,1
2,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1,0,1,0,0
3,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0,0,1,0,0
4,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,NaN,5,0.00,2,1,0,96270.64,0,1,1,0,0
9996,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0,1,1,0,0
9997,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1,0,1,0,0
9998,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1,1,0,1,0
9999,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0,0,1,0,0

In [159]:

df_dummies = pd.get_dummies(df)

In [163]:
df_dummies = df_dummies.fillna(0).astype(int)
df_dummies.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_Label,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0,1,1,1,101348,1,0,1,0,0,1,0
1,608,41,1,83807,1,0,1,112542,0,0,0,0,1,1,0
2,502,42,8,159660,3,1,0,113931,1,0,1,0,0,1,0
3,699,39,1,0,2,0,0,93826,0,0,1,0,0,1,0
4,850,43,2,125510,1,1,1,79084,0,0,0,0,1,1,0

**Double Encoding**

In [165]:
df_dummies_1 = pd.get_dummies(df, drop_first=True)
df_dummies_1.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_Label,Geography_Germany,Geography_Spain,Gender_Male
0,619,42.0,2,0.00,1,1,1,101348.88,1,0,False,False,False
1,608,41.0,1,83807.86,1,0,1,112542.58,0,0,False,True,False
2,502,42.0,8,159660.80,3,1,0,113931.57,1,0,False,False,False
3,699,39.0,1,0.00,2,0,0,93826.63,0,0,False,False,False
4,850,43.0,2,125510.82,1,1,1,79084.10,0,0,False,True,False

In [166]:
df_dummies_1 = df_dummies_1.fillna(0).astype(int)
df_dummies_1.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_Label,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0,1,1,1,101348,1,0,0,0,0
1,608,41,1,83807,1,0,1,112542,0,0,0,1,0
2,502,42,8,159660,3,1,0,113931,1,0,0,0,0
3,699,39,1,0,2,0,0,93826,0,0,0,0,0
4,850,43,2,125510,1,1,1,79084,0,0,0,1,0

**Targer Encoder**

In [177]:
df_1 = pd.read_csv('Churn_Modelling.csv')
df_1.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [184]:
df_1.drop(columns=['CustomerId', 'Surname', 'RowNumber'], axis = 1, inplace = True)

In [187]:
df_1['Gender'] = df_1['Gender'].fillna('Male')

In [188]:
from category_encoders import TargetEncoder

In [189]:
encoder = TargetEncoder()

df_1['Gender Encoded'] = encoder.fit_transform(df_1['Gender'], df_1['Exited'])
df_1.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender Encoded
0,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1,0.250664
1,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0,0.250664
2,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1,0.250664
3,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0,0.250664
4,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0,0.250664

In [190]:
df_1['Gender Encoded'].value_counts()

Gender Encoded
0.165026    5484
0.250664    4516
Name: count, dtype: int64

**Benefits of TE:**

Target encoding is a simple and quick encoding method that doesn't add to the dimensionality of the dataset. Therefore, it may be used as a good first try technique

**Limitations of TE:**

It is dependent on the target distribution which means target encoding requires careful validation as it can be prone to overfitting.

**Hash Encoding**

In [191]:
from category_encoders import HashingEncoder

In [198]:
X= df_1.Gender

In [199]:
y = df_1.Exited

In [200]:
He = HashingEncoder(cols = ['Gender'])
He.fit_transform(X,y)

      col_0  col_1  col_2  col_3  col_4  col_5  col_6  col_7
0         0      0      0      0      0      0      0      1
1         0      0      0      0      0      0      0      1
2         0      0      0      0      0      0      0      1
3         0      0      0      0      0      0      0      1
4         0      0      0      0      0      0      0      1
...     ...    ...    ...    ...    ...    ...    ...    ...
9995      0      0      0      0      0      1      0      0
9996      0      0      0      0      0      1      0      0
9997      0      0      0      0      0      0      0      1
9998      0      0      0      0      0      1      0      0
9999      0      0      0      0      0      0      0      1

[10000 rows x 8 columns]

In [201]:
X= df.Geography

In [203]:
He = HashingEncoder(cols =['Geography'])
He.fit_transform(X,y)

      col_0  col_1  col_2  col_3  col_4  col_5  col_6  col_7
0         1      0      0      0      0      0      0      0
1         0      0      0      0      0      0      0      1
2         1      0      0      0      0      0      0      0
3         1      0      0      0      0      0      0      0
4         0      0      0      0      0      0      0      1
...     ...    ...    ...    ...    ...    ...    ...    ...
9995      1      0      0      0      0      0      0      0
9996      1      0      0      0      0      0      0      0
9997      1      0      0      0      0      0      0      0
9998      0      1      0      0      0      0      0      0
9999      1      0      0      0      0      0      0      0

[10000 rows x 8 columns]

In [205]:
He = HashingEncoder(n_components=16, cols = ['Geography'])
He.fit_transform(X,y)

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10,col_11,col_12,col_13,col_14,col_15
0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
9996,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
9997,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
9998,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
9999,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0

**Why use Hashing Encoder despite collisions?**

1.Because it offers major practical benefits:

2.Memory efficient

3.Very fast

4.Handles millions of categories

5.Works with unseen categories automatically

6.No need to store a category-to-index mapping